version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * 2,5"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "10 9 * * 2,5"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "20 9 * * 2,5"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "30 9 * * 2,5"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
